# Sample workflow to access AWS resources when workflow is tied to branch
# The workflow Creates static website using aws s3
name: S3 workflow
on:
  workflow_dispatch:
permissions:
  id-token: write # This is required for aws oidc connection
  contents: read # This is required for actions/checkout
jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: samplerolesession
          aws-region: ${{ secrets.AWS_REGION }}
      # Upload a file to AWS s3
      - name:  Copy index.html to s3
        run: |
          aws s3 cp ./index.html s3://${{ secrets.AWS_BUCKET_NAME }}/